### PR TITLE
Add manually corrected dwi SC segmentations

### PR DESCRIPTION
**Pull request by valosekj**
This PR contains manually corrected dwi SC segmentations for following subjects:

```
FILES_SEG:
- sub-vuiisAchieva01_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
- sub-vuiisAchieva06_dwi_moco_dwi_mean.nii.gz
- sub-perform03_dwi_moco_dwi_mean.nii.gz
- sub-stanford01_dwi_moco_dwi_mean.nii.gz
- sub-sapienza01_dwi_moco_dwi_mean.nii.gz
- sub-mniS03_dwi_moco_dwi_mean.nii.gz
- sub-perform01_dwi_moco_dwi_mean.nii.gz
- sub-beijingVerio02_dwi_concat_moco_dwi_mean.nii.gz
- sub-vuiisAchieva04_dwi_moco_dwi_mean.nii.gz
```

Some of corrected segmentations have poor quality of background data; see https://github.com/spine-generic/data-multi-subject/issues/14.

Below is zipped QC report.

[qc_corr_20200729205726.zip](https://github.com/spine-generic/data-multi-subject/files/4997302/qc_corr_20200729205726.zip)

### CODE REVIEW

**Review by jcohenadad — CHANGES_REQUESTED** [review]
i would just update the segmentation below so the SC shape is more realistic (the segmentation extends over an artifact)-- otherwise it looks good 💯 

Screen Shot 2020-07-29 at 4 43 31 PM

**Comment by valosekj** [comment]
> i would just update the segmentation below so the SC shape is more realistic (the segmentation extends over an artifact)

Updated in https://github.com/spine-generic/data-multi-subject/pull/15/commits/75c2bdb1b2684aac745c75061223db95c0d255b8 :

image

updated QC for this sub:
[qc_corr_20200730080920.zip](https://github.com/spine-generic/data-multi-subject/files/4999164/qc_corr_20200730080920.zip)

**Review by jcohenadad — APPROVED** [review]

**Comment by jcohenadad** [comment]
@valosekj for info: i've started to draft a new release: https://github.com/spine-generic/data-multi-subject/releases/tag/untagged-eaf7e036d8e8a0fb7c24

**Comment by valosekj** [comment]
> @valosekj for info: i've started to draft a new release: https://github.com/spine-generic/data-multi-subject/releases/tag/untagged-eaf7e036d8e8a0fb7c24

The link does not work -- "page not found"

**Comment by jcohenadad** [comment]
> The link does not work -- "page not found"

interesting, i thought drafts were publicly shareable but i guess not

**Comment by valosekj** [comment]
Newly created QC with `sg_manual_correction -config err_file_dwi_valosek_29-07-2020.yml -qc-only`:

[qc_corr_20200731162412.zip](https://github.com/spine-generic/data-multi-subject/files/5008261/qc_corr_20200731162412.zip)

(this is a duplication of comment https://github.com/spine-generic/spine-generic/pull/160#issuecomment-667148208. I post QC also here, because it is related to this PR.)

**Pull request merged**
