### PR TITLE
Fix wrong defacing in some images

### LINKED ISSUE #22: Fix wrong defacing in some subjects
After finding issue with defacing https://github.com/spine-generic/data-multi-subject/issues/9#issuecomment-665953657, we decided to re-review all the defacing results.

### PR DESCRIPTION
**Pull request by alexfoias**
This PR fixes the remaining issues with defacing.
Fixes #22

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad This PR is ready for review.

**Review by jcohenadad — CHANGES_REQUESTED** [review]
pls do not change the chmod

**Comment by alexfoias** [comment]
Fixed in https://github.com/spine-generic/data-multi-subject/pull/19/commits/0b2399908b823deb0125df70fde74f9547e8da89

Screen Shot 2020-07-31 at 12 09 54 PM

**Comment by alexfoias** [comment]
The issues signalled here: https://github.com/spine-generic/data-multi-subject/pull/21#issuecomment-667390603
- sub-cmrra02: fixed T2w Screen Shot 2020-07-31 at 10 29 55 AM
- sub-cmrra04 & sub-cmrra05 : we received the T2w images like that.
- sub-oxfordFmrib07: fixed T1w Screen Shot 2020-08-03 at 10 05 14 AM
- sub-dresden02: fixed T2w Screen Shot 2020-08-03 at 10 07 46 AM
- sub-stanford06: fixed T1w Screen Shot 2020-08-03 at 10 10 04 AM

**Comment by jcohenadad** [comment]
@alexfoias the image shown in https://github.com/spine-generic/data-multi-subject/pull/19#issue-460200227 is not representative of the problem (it is representative of the solution)--

**Comment by jcohenadad** [comment]
> * sub-cmrra04 & sub-cmrra05 : we received the T2w images like that.

@alexfoias are you sure?  `sub-cmrra02_T2w.nii.gz` , which you were able to fix, is coming from the same site

**Comment by alexfoias** [comment]
The data that we have from the backup look like this:

Screen Shot 2020-08-03 at 10 30 30 AM
Screen Shot 2020-08-03 at 10 30 36 AM

**Comment by jcohenadad** [comment]
and how does sub-cmrra02_T2w.nii.gz look like? are the other files in the backup not defaced?

**Comment by alexfoias** [comment]
All the data from cmrr* came defaced.

**Comment by jcohenadad** [comment]
> All the data from cmrr* came defaced.

so how come you were able to "reface" cmrra02?

also see my other question https://github.com/spine-generic/data-multi-subject/pull/19#issuecomment-668058959 
_are the other files in the backup not defaced?_

**Comment by alexfoias** [comment]
cmrra02 wasn't refaced. The initial file wasn't as chopped as the one that we uploaded before.
All the data from cmrr are defaced. [Here](https://github.com/spine-generic/data-multi-subject/files/5016704/qc_cmrr.zip) is a QC of the data from the recovered backup (before defacing of the complete multiSubject).

**Comment by jcohenadad** [comment]
> cmrra02 wasn't refaced

> All the data from cmrr* came defaced.

🧐

**Comment by alexfoias** [comment]
I mixed up things on my fork. I'll close this PR and open a new one with the clean changes.

**Pull request closed without merging**
