### PR TITLE
derivatives/labels folder and csfseg-manual masks

### PR DESCRIPTION
**Pull request by charleygros**
### Done:
- create `derivatives/labels` folder
- push some manual segmentation masks of CSF

### CODE REVIEW

**Comment by charleygros** [comment]
@jcohenadad : We may want to agree and document the naming convention for label files (seg, labels...etc)

For now, these files are named with `_csfseg-manual` suffix.

**Comment by jcohenadad** [comment]
oopsi! the labels should go under another labels/ folder?? i forgot about that. I guess i'll have to fix it in this other repos: https://github.com/spine-generic/data-single-subject/tree/master/derivatives

**Comment by jcohenadad** [comment]
> @jcohenadad : We may want to agree and document the naming convention for label files (seg, labels...etc)

yup! → https://github.com/spine-generic/data-multi-subject/issues/6

> For now, these files are named with `_csfseg-manual` suffix.

sounds great to me!

**Review by jcohenadad — APPROVED** [review]
i haven't checked the labels but i trust they are good 👍

**Comment by jcohenadad** [comment]
@charleygros you can merge when you want

**Pull request merged**
