### PR TITLE
manual correction of t1w and t2w images

### PR DESCRIPTION
**Pull request by PaulBautin**
This PR contains manually corrected t1w and t2w SC segmentations for following subjects:

FILES_SEG:
  - sub-tokyo750w02_T2w_RPI_r.nii.gz
  - sub-tokyo750w04_T1w_RPI_r.nii.gz
  - sub-tokyo750w06_T2w_RPI_r.nii.gz
  - sub-perform02_T1w_RPI_r.nii.gz
  - sub-perform02_T2w_RPI_r.nii.gz
  - sub-perform03_T2w_RPI_r.nii.gz
  - sub-brnoUhb02_T1w_RPI_r.nii.gz
  - sub-brnoUhb05_T1w_RPI_r.nii.gz
  - sub-strasbourg05_T2w_RPI_r.nii.gz
  - sub-cmrra02_T2w_RPI_r.nii.gz
  - sub-cmrrb05_T1w_RPI_r.nii.gz
  - sub-brnoUhb07_T1w_RPI_r.nii.gz
  - sub-beijingVerio04_T2w_RPI_r.nii.gz
  - sub-vuiisIngenia05_T2w_RPI_r.nii.gz
  - sub-brnoUhb08_T1w_RPI_r.nii.gz
  - sub-beijingGE03_T1w_RPI_r.nii.gz
  - sub-pavia04_T1w_RPI_r.nii.gz

FILES_GMSEG:
  - sub-sapienza04_T2star_rms.nii.gz
  - sub-sapienza01_T2star_rms.nii.gz

FILES_LABEL:
  - sub-brnoUhb01_T1w_RPI_r.nii.gz
  - sub-brnoUhb08_T1w_RPI_r.nii.gz

-Very little correction was applied to GMSEG because of the difficulty to localize grey matter
-sub-cmrra02_T2w_RPI_r.nii.gz was not corrected because of defacing problem

Below is zipped QC report: (Second zip file contains corrections of first file for):
FILES_SEG:
 - sub-cmrra02_T2w_RPI_r.nii.gz
 - sub-cmrrb05_T1w_RPI_r.nii.gz
 - sub-vuiisIngenia05_T2w_RPI_r.nii.gz
 - sub-pavia04_T1w_RPI_r.nii.gz

FILES_GMSEG:
 - sub-sapienza04_T2star_rms.nii.gz

FILES_LABEL:
  - sub-brnoUhb01_T1w_RPI_r.nii.gz
  - sub-brnoUhb08_T1w_RPI_r.nii.gz

[qc_corr_20200729145633.zip](https://github.com/spine-generic/data-multi-subject/files/5002276/qc_corr_20200729145633.zip)
[qc_corr_20200730095951.zip](https://github.com/spine-generic/data-multi-subject/files/5002277/qc_corr_20200730095951.zip)

### CODE REVIEW

**Comment by jcohenadad** [comment]
@PaulBautin you need to click inside the spinal cord:

Screen Shot 2020-07-30 at 11 50 58 AM

**Comment by jcohenadad** [comment]
@PaulBautin i can see that some data are of very poor quality-- can you please start modality-specific issues about data quality as @valosekj did in #14?

**Comment by jcohenadad** [comment]
from what i see we can exclude:
- sub-pavia04_T1w_RPI_r.nii.gz
- sub-cmrrb05_T1w_RPI_r.nii.gz
- sub-sapienza04_T2star_rms.nii.gz

**Comment by jcohenadad** [comment]
@PaulBautin i'm looking at both zip files, and some images appear in both zip files, which:
- is confusing
- makes reviewing inefficient (reviewer looks at the same file twice).

could you please re-upload a proper qc, without duplication? thanks

**Comment by PaulBautin** [comment]
I have corrected labeling, see QC:
[qc_corr_20200730115633.zip](https://github.com/spine-generic/data-multi-subject/files/5002403/qc_corr_20200730115633.zip)

Is there a reason not to allow "none type" input in a section of the config yaml file? sg_manual_correction did not allow to only do labelling corrections.

**Comment by jcohenadad** [comment]
> I have corrected labeling, see QC:
> [qc_corr_20200730115633.zip](https://github.com/spine-generic/data-multi-subject/files/5002403/qc_corr_20200730115633.zip)

the qc also contains segmentations, which is confusing

> Is there a reason not to allow "none type" input in a section of the config yaml file? sg_manual_correction did not allow to only do labelling corrections.

just remove the FILES_SEG and FILES_GMSEG entries in your config file-- or you can also open an issue so we can fix it at some point

**Comment by valosekj** [comment]
> > Is there a reason not to allow "none type" input in a section of the config yaml file? sg_manual_correction did not allow to only do labelling corrections.
> 
> just remove the FILES_SEG and FILES_GMSEG entries in your config file-- or you can also open an issue so we can fix it at some point

It is probably same thing as I mentioned in [this issue](https://github.com/spine-generic/spine-generic/issues/151). I would vote for clarifying [doc](https://spine-generic.readthedocs.io/en/latest/analysis_pipeline.html#segmentation-and-vertebral-labeling) -- add a sentence/hint something like: "If you want to correct only labeling, include in your config yml file only `FILES_LABEL` key, i.e., do not include/delete `FILES_SEG` and `FILES_GMSEG` keys, and vice versa."

**Comment by PaulBautin** [comment]
new QC with command: `sg_manual_correction -config err_file_t1w_t2w_corrected.yml -path-in data_to_correct -qc-only`
[qc_corr_20200731105752.zip](https://github.com/spine-generic/data-multi-subject/files/5007848/qc_corr_20200731105752.zip)

**Comment by jcohenadad** [comment]
@PaulBautin can you pls remove `sub-cmrra02_T2w_RPI_r.nii.gz` from the manual correction, because there is the problem with the data, i.e., this should not be part of the "manual correction" PR.

**Comment by jcohenadad** [comment]
@PaulBautin also remove `sub-sapienza04_T2star_rms.nii.gz`, where the segmentation is meaningless because of poor data quality. 

also: this manual corr is not complete: 
image

**Comment by PaulBautin** [comment]
DONE:
- remove cmrra02 from derivatives
- remove sapienza04 t2* from derivatives
- correct gmseg for sapienza01 t2*
image

new QC:
[qc_corr_20200731122832.zip](https://github.com/spine-generic/data-multi-subject/files/5008011/qc_corr_20200731122832.zip)

**Review by jcohenadad — APPROVED** [review]
Awesome work @PaulBautin 💯

**Pull request merged**
